version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: schulbuchaktion



volumes:
  mysql_data: